name: Deploy Tailwind CSS to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install -D tailwindcss postcss autoprefixer

    # Step 4: Build Tailwind CSS
    - name: Build CSS
      run: npx tailwindcss -i ./assets/css/styles.css -o ./assets/css/styles.css --minify

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Directory with the built files
        publish_branch: gh-pages
